version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - echo Installing required libs...
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - build/**/*
    - config/**/*
    - scripts/**/*
